### PR TITLE
Allow mapping Target Datasources that have less allocated space than Source Datastores - addresses #345

### PR DESCRIPTION
**Pull request by AparnaKarve**
Allow mapping Target Datasources that have less allocated space than Source Datastores

Before -
screen shot 2018-06-20 at 10 05 49 am

After (no numerical information) -
screen shot 2018-06-20 at 10 04 32 am

Fixes https://github.com/ManageIQ/miq_v2v_ui_plugin/issues/345

### CODE REVIEW

**Comment by AparnaKarve** [comment]
@michaelkro Can you please review this?

The PR is mostly red than green  -- a lot of deleted code for all the current safeguards that check for space limitations. BTW, great job with those safeguards!

I have also removed all inapplicable tests.
I am planning to add tests that check what icon we render in the tree based on the available space -- but since there is some urgency around this, I think we should get this merged soon, and I can work on the test as time permits. Thanks.

**Comment by michaelkro** [comment]
In case we decide that we want to format the negative disk space totals in the future (numeral.js does not have support for this at the moment), a workaround is described in the comments of this [issue](https://github.com/adamwdraper/Numeral-js/issues/222)

I think

**Comment by AparnaKarve** [comment]
@michaelkro It looks like `showAlertAction` is being used in `componentWillReceiveProps`, so can't delete that.

**Comment by michaelkro** [comment]
Hey @AparnaKarve, I think the CI failures are due to [these guys](https://github.com/ManageIQ/miq_v2v_ui_plugin/blob/master/app/javascript/react/screens/App/Overview/screens/MappingWizard/components/MappingWizardDatastoresStep/MappingWizardDatastoresStep.js#L101-L102)

My fault, I totally forgot about those

**Comment by AparnaKarve** [comment]
@michaelkro No problem!
I think `hideAlertAction` can be cleaned up... so doing that now.

**Comment by AparnaKarve** [comment]
@vconzola Is it OK to display a negative value for Available space?
If not, please suggest an alternative.

Note that, the tree component does not support tooltips currently.

**Comment by vconzola** [comment]
@AparnaKarve After discussing with @priley86 I think having negative available space will be confusing. Also, since the source side is showing allocated space and not actual consumed space the available space value isn't accurate anyway. I suggest we remove the Available space from the mapped tree view altogether. I'll confirm with Brett/Marco that's OK and if so, I'll open a new issue for this.

**Comment by AparnaKarve** [comment]
@vconzola Agree that displaying negative available space is not ideal.

Other than the mapped tree view, we also display negative available space in the `Target Datastores`, as seen in the screenshot.

I will mark this PR as a WIP until we decide the exact course of action here.
Thanks.

**Comment by AparnaKarve** [comment]
@vconzola Per our discussion, I have removed all numerical information associated with Datastores.
Please review the Before and After screens above.
Thanks.

**Comment by AparnaKarve** [comment]
@priley86 @michaelkro If this is looking good, can you merge this? Pretty please?? :)

**Comment by michaelkro** [comment]
Looks good!

**Comment by simaishi** [comment]
Marking as conflict for now, as something is strange with this PR and the merge commit (which is needed for backport) doesn't seem to show up.... @AparnaKarve will create a separate PR.

**Comment by AparnaKarve** [comment]
@simaishi Created Gaprindashvili PR - #486

**Comment by Fryguy** [comment]
@michaelkro How are you merging?  Are you using github Green Button or doing something from your CLI?

**Comment by Fryguy** [comment]
I just noticed that for some reason "rebase merging" was enabled on this repo when it shouldn't have been, so if that was used that explains why @simaishi can't find the merge commit, because there isn't one.  I've disabled that, since we prefer merge commit style merging across the org.

cc @michaelkro @priley86 @AparnaKarve @AllenBW

**Comment by michaelkro** [comment]
@Fryguy We were using the "rebase and merge" button before coming into the fold, sorry about that!

**Comment by simaishi** [comment]
Backported to Gaprindashvili via https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/492

**Pull request merged**
