### PR TITLE
rails controllers - use default set of action filters, including check_privileges

### PR DESCRIPTION
**Pull request by himdel**
The current controllers seem to do no request checking whatsoever - adding the standard set of filters.

### CODE REVIEW

**Comment by AparnaKarve** [comment]
@himdel The changes in this PR looked seemingly harmless and something that we do across the board for all our controllers in Classic UI...plus these are RBAC related changes, and hence are necessary.
Although I just found out that the `session` information is not carried over to the plugin controllers.
As a result, `check_privileges` cannot retrieve `session[:userid]`.
Any idea if the plugin engine is missing some `session` related settings?

**Comment by himdel** [comment]
@AparnaKarve interesting problem .. where is this happening?

Trying ui-classic master and v2v master, I can see `session[:userid]` just fine.. 

(Any chance the session just timed out?)

**Comment by AparnaKarve** [comment]
@himdel Ok, so the method that I'm testing is `download_migration_log` in `migration_log_controller`.

Will be testing a couple things today, and will get back to you with more info.
(stay tuned :) )

Session did not timeout -- without `check_privileges` everything seems to work.

**Comment by himdel** [comment]
Aah, thanks, I was looking in the other controller.. Testing :)

And eagerly awaiting more bugs ;)

**Comment by himdel** [comment]
@AparnaKarve Aaaah, found it :)

```diff
diff --git a/app/javascript/react/screens/App/Plan/PlanActions.js b/app/javascript/react/screens/App/Plan/PlanActions.js
index 0c3208f..8cd7ffe 100644
--- a/app/javascript/react/screens/App/Plan/PlanActions.js
+++ b/app/javascript/react/screens/App/Plan/PlanActions.js
@@ -86,7 +86,7 @@ export const downloadLogAction = task => dispatch => {
   dispatch({
     type: FETCH_V2V_MIGRATION_TASK_LOG,
     payload: new Promise((resolve, reject) => {
-      API.get(`/migration_log/download_migration_log/${task.id}`)
+      http.get(`/migration_log/download_migration_log/${task.id}`)
         .then(response => {
           resolve(response);
           dispatch({
```

it's happening because `API.get` doesn't send the authentication cookie (only the API token).
(Presumably the old `API` implementation used to send both, now we have `http` for rails queries and `API` for API queries)

=> (pr)

**Comment by AparnaKarve** [comment]
getting this --

```
I, [2018-05-22T10:30:27.013314 #67019]  INFO -- : Started GET "/migration_log/download_migration_log/1" for 127.0.0.1 at 2018-05-22 10:30:27 -0700
I, [2018-05-22T10:30:27.093389 #67019]  INFO -- : Processing by MigrationLogController#download_migration_log as */*
I, [2018-05-22T10:30:27.093516 #67019]  INFO -- :   Parameters: {"id"=>"1"}
I, [2018-05-22T10:30:27.096308 #67019]  INFO -- : Redirected to http://localhost:8080/dashboard/login?timeout=false
I, [2018-05-22T10:30:27.096447 #67019]  INFO -- : Filter chain halted as :check_privileges rendered or redirected
I, [2018-05-22T10:30:27.096612 #67019]  INFO -- : Completed 302 Found in 3ms (ActiveRecord: 0.0ms)

```

-- which is because `session[:userid]` is nil

**Comment by AparnaKarve** [comment]
Here's some data that may help troubleshoot further -


```diff
--- a/app/controllers/migration_controller.rb
+++ b/app/controllers/migration_controller.rb
@@ -1,7 +1,9 @@
 # Migration controller - mostly service to initialize the react top level component
 # and to handle the initial routing endpoint.
 class MigrationController < ApplicationController
+  before_action :get_session_data
   before_action :check_privileges
+  before_action :set_session_data
   after_action :cleanup_action
 
   def index
@@ -9,5 +11,13 @@ class MigrationController < ApplicationController
     @layout = 'migration'
   end
 
+  def get_session_data
+    p session[:userid] #shows admin
+  end
+
+  def set_session_data
+    p session[:userid] #shows admin -- so no need to set it again
+  end
+

```

```diff
--- a/app/controllers/migration_log_controller.rb
+++ b/app/controllers/migration_log_controller.rb
@@ -1,4 +1,5 @@
 class MigrationLogController < ApplicationController
+  before_action :get_session_data
   before_action :check_privileges
   after_action :cleanup_action
 
@@ -17,4 +18,8 @@ class MigrationLogController < ApplicationController
       :status_message => task_message
     }
   end
+
+  def get_session_data
+    p session[:userid] # shows nil
+  end
```

**Comment by himdel** [comment]
Ok, I'll have to set up some done migrations to test this .. the problem is likely still in the `http` code (it's not really used yet, as we have `$http` for angular and `miqJqueryRequest` for the old code).

I'm thinking it probably sends just the CSRF token and not the cookie..

I'll ping you in the evening or tomorrow, thanks :)

**Comment by AparnaKarve** [comment]
Thanks! Appreciate your time on this :)

If there is anything else that I can help with, please let me know!

**Comment by himdel** [comment]
Doubtlessly there will, thanks :)

But for now, https://github.com/ManageIQ/manageiq-ui-classic/pull/3978 *should* be the second piece to get https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/340 working.  (Needs webpack for the change to have effect.)

**Pull request merged**
