### PR TITLE
[GAPRINDASHVILI] Adjusts printwidth to 120, ignores all strings for intl that exceed

### PR DESCRIPTION
**Pull request by AllenBW**
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1596264

Its like  #443 CEPT FOR **G**

cc @mzazrivec

🎁

### CODE REVIEW

**Comment by AllenBW** [comment]
thanks @kedark3 for the bz!!!! <3 🙇

**Comment by mzazrivec** [comment]
Merge anyone? I'd like to rebase https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/440 on top of this one (thanks Allen).

**Comment by AparnaKarve** [comment]
@simaishi Can you do the honors here? Thanks.

**Comment by simaishi** [comment]
@AllenBW @mzazrivec  Both this PR and https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/440 are needed for https://bugzilla.redhat.com/show_bug.cgi?id=1596264 ?

**Comment by AllenBW** [comment]
@simaishi correct! yeah its a catchall translation bz 😋

**Comment by mzazrivec** [comment]
@simaishi Yup, although I have to rebase https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/440 before it can be merged.

**Comment by AllenBW** [comment]
😭 ok will get to this in a bit

**Comment by AllenBW** [comment]
@simaishi okie dokie, we're g2g, yah did the right thing thou... this one was gonna cause trouble either way, either everything else backported would break or this one would, much prefer the single place to fix 😏 💟

**Pull request merged**
