### PR TITLE
Show the archived plans in the Archived Plan view

### PR DESCRIPTION
**Pull request by AparnaKarve**
A slight correction required in https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/493

@AllenBW Please review.

### CODE REVIEW

**Comment by bthurber** [comment]
@AllenBW please add the transformation label to this.

**Comment by bthurber** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1610377

**Comment by simaishi** [comment]
@AparnaKarve If that line needs to look like
```
finishedTransformationPlans={Immutable.asMutable(archivedTransformationPlans, { deep: true })}
```
after backport, both https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/493 and this PR need to be `gaprindashvili/yes` as https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/493 is what added `Immutable` and `{ deep: true })`. Otherwise, backport of this PR will be a no-op.

**Comment by AparnaKarve** [comment]
@simaishi Agreed.
I have set #493 to `gaprindashvili/yes`.
Can you backport #493 and then retry the backport here?
Thanks.

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 23029d76d7e63fc9e4a5e5a4544a91ba4efdeb6b
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Mon Jul 16 19:59:09 2018 -0400

    Merge pull request #494 from AparnaKarve/fix_archived_plan_view
    
    Show the archived plans in the Archived Plan view
    (cherry picked from commit c438212df77823a2d0fb3562971089dade1f9163)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1610390
```

**Pull request merged**
