### PR TITLE
[WIP][#370] Cancel Migration Plan / Cancel Mike's Plans

### LINKED ISSUE #370: User can cancel a migration in progress
User can cancel a migration.  Need to finalize the requirements here:
- is cancel action only enabled/available for migrations in progress
- cancel confirmation should be shown

### PR DESCRIPTION
**Pull request by mturley**
Okay. So, this one is a doozy for a few reasons:

* It comes during a pretty tumultuous time where I have had a good half of my productive hours consumed by unexpected personal time-- i'll loop back with Cat about that to be sure it's reflected correctly.. 🤔 
* I made these two Redux commits on Friday and Wednesday, with the assumption that it was a single JSON property we were going to plug in for a whole plan's cancellation-- I missed the memo that we had an API for task cancellation until it was in my lap, which is my own fault. So I've done some rework since these commits that isn't ready to push quite yet.
* I have been working on the React side of things since these, because I wanted to jump to doing things top-down like I started doing with #399. So, these Redux commits for an action to cancel the entire plan might not be wasted, but they need to live alongside other Redux work. @priley86 maybe this is where you can help me today. I'm sorry I didn't ask sooner, I wanted to just get things together and get it all done. It's really not much work...
* Some other things I can't think of, there's a meeting in 3 minutes, I'm going to stop typing now.

Needed to get the PR number to start making this rebase real, i've got commits to push this evening. Thanks again guys.

This will close #370, I promise

### CODE REVIEW

**Comment by mturley** [comment]
@AllenBW I screwed up the PR naming again, can ya fix it for me?

**Comment by mturley** [comment]
Oops, I missed the Issue number too. 1 sec.

**Comment by AllenBW** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1564257

**Comment by priley86** [comment]
I would go ahead and rebase this on top of #442 (since it also touches Plan Details screen) @mturley. I'm working the Redux pieces now...

**Comment by mturley** [comment]
Closing this one, we are using Patrick's PR #511 instead.

**Pull request closed without merging**
