### PR TITLE
Use standard application layout

### PR DESCRIPTION
**Pull request by himdel**
v2v currently bakes its own application layout, which is problematic because it means v2v is currently managing all the assets for itself.

Meaning any changes in manageiq application layout can currently break v2v.

Since v2v does not need to override the menu, navbars etc, it should be using the standard manageiq layout, and only affecting `center_div`.

This PR does just that.
Depends on https://github.com/ManageIQ/manageiq-ui-classic/pull/3965  for `<title>` to work right (merged, not backported yet)

https://github.com/ManageIQ/manageiq-ui-classic/issues/3963: needed to be compatible with both master and gaprindashvili

### CODE REVIEW

**Comment by himdel** [comment]
Note that this may or may not be 100% there: looks like we would need to move the content one layer up to get rid of extra margins.

If that's a concern, we can wait for an ops UI PR to add a layout without margins.

**Comment by priley86** [comment]
thanks! will test this shortly...

**Comment by priley86** [comment]
@himdel yes, we will need the added margins it seems...would like to maintain this UI design if possible.

**Comment by himdel** [comment]
Makes sense, on it today :)

---

Before (master, master):

before



After (cpr, #331):

TODO

**Comment by himdel** [comment]
@priley86 Ok, with https://github.com/ManageIQ/manageiq-ui-classic/pull/3970 this should be working again :)

Bonus: we're using `<body>` now ;)

**Comment by priley86** [comment]
ok testing this now...

**Comment by priley86** [comment]
this looks good to me - tested the layout is applying the same way as before.

@Fryguy - you may want to incorporate this into your branch...

**Comment by priley86** [comment]
@AparnaKarve can you confirm?

**Comment by AparnaKarve** [comment]
@himdel @priley86 The Migration screen does not seem to be rendering well for me.

screen shot 2018-05-22 at 12 48 45 pm

Also seeing an error in the browser console -
screen shot 2018-05-22 at 12 55 09 pm

@himdel Can you try again at your end?

**Comment by priley86** [comment]
hmm - i reupdated core miq, ui-classic and targeted this branch...can you try again?

**Comment by AparnaKarve** [comment]
@himdel @priley86 Ignore my above comment... :) and sorry for the noise

I rebased ui-classic and things are back to normal now.

Layout looks good! (like it was before)

**Pull request merged**
