### PR TITLE
[#240] Plan Wizard: Select valid VMs by default on CSV import, but not in discovery mode

### LINKED ISSUE #240: Plan Wizard - VM Import selection state
* If user selects "discover" option, deselect all VMs by default.
* If user select "CSV Import option, after the import, select all valid VMs by default.

cc: @vconzola @serenamarie125 @AparnaKarve

### PR DESCRIPTION
**Pull request by mturley**
Fixes #240 

9e33eg2ped

### CODE REVIEW

**Comment by bthurber** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1610382

**Comment by bthurber** [comment]
@AparnaKarve please add the transformation label.

**Comment by AparnaKarve** [comment]
@bthurber The `transformation` label is applicable to the core MIQ repo to identify PRs that are meant for v2v.
This entire repo (miq_v2v_ui_plugin) is meant for v2v only, so `transformation` is kinda implicit - but if it helps the backporting process in any way, let's add it.

I have added the label.

**Comment by AllenBW** [comment]
Its just such a pretty label 😍

**Pull request merged**
