### PR TITLE
Adds ellipsis to migration not started description field

### LINKED ISSUE #448: Description of migration plan should be wrapped, not float over VM Count
https://bugzilla.redhat.com/show_bug.cgi?id=1596286

screenshot from 2018-06-28 10-14-37 1

😭 🌮

### PR DESCRIPTION
**Pull request by AllenBW**
fixes #448

screen shot 2018-06-28 at 11 18 22 am

cc @kedark3

### CODE REVIEW

**Comment by AllenBW** [comment]
KK informed me this was a slightly bigger issue than initially thought... apparently description overflow makes clicking the migrate button IMPOSSIBLE 😭 so this will likely turn into a blocker?  flagging gyes in anticipation of that

**Comment by priley86** [comment]
ok to merge to @AparnaKarve ?

**Comment by kedark3** [comment]
Kindly check the same with Migration Completed Screen. I think issue exists there as well.

**Comment by AllenBW** [comment]
@kedark3 we do not descriptions on other screens... 👍 🙇

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit e37b0fca5ce6d1fad91dba8201a1a508592de2c5
Author: Aparna Karve <aparna.karve@gmail.com>
Date:   Thu Jun 28 12:14:37 2018 -0700

    Merge pull request #449 from AllenBW/bug/#488-migration-description-overflow
    
    Adds ellipsis to migration not started description field
    (cherry picked from commit dd5f0bd5db4033b752a5406bdc1d058447502a95)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1596777
```

**Comment by simaishi** [comment]
Travis failure fixed in https://github.com/ManageIQ/miq_v2v_ui_plugin/pull/457

**Pull request merged**
